services:
  - type: web
    name: lodge-management
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py app:app
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FIREBASE_CREDENTIALS
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: RENDER
        value: "true"
