services:
  - type: web
    name: lodge-management
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120 --workers 2 --threads 4 --preload
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_CREDENTIALS
        sync: false